// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import TryitController from "./tryit_controller"
application.register("tryit", TryitController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)
